[package]
name = "integration-service"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.8.5", features = ["postgres", "runtime-tokio-rustls"] }
tokio = { version = "1", features = ["full"] }